jwt_secret_path: "/run/secrets/jwt_secret"
grpc:
  port: 50053
  timeout: 1m
spot:
  grpc_addr: "spot-server:50052"
postgres:
  link: "postgres://admin:admin@OrderPostgres:5432/order?sslmode=disable"
  max_retries: 10
  max_connections: 10
  min_connections: 2
redis:
  addr: "redis:6379"
  password: "admin"
  db: 0
  max_retries: 10
  dial_timeout: 10s
  timeout: 5s