env: ".env"
token_ttl:
  refresh_token_ttl: 168h
  access_token_ttl: 12h
grpc:
  port: 50051
  timeout: 1m
postgres:
  link: "postgres://admin:admin@db:5432/db?sslmode=disable"
  max_retries: 10
redis:
  addr: "redis:6379"
  password: "admin"
  db: 0
  max_retries: 10
  dial_timeout: 10s
  timeout: 5s
limiter:
  capacity: 5
  refill_rate_in_minutes: 1m